version: '3'
services:
  database:
    image: bitnami/postgresql:11-debian-9
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_PASSWORD=testpasswd
      - POSTGRESQL_USERNAME=testuser
      - POSTGRESQL_DATABASE=testdb
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repuser
      - POSTGRESQL_REPLICATION_PASSWORD=reppassword
    networks:
      hakhak_net:
        ipv4_address: 172.16.25.2
  server:
    build:
      context: .
      dockerfile: ./dev.dockerfile
    ports:
      - '80:3000'
    volumes:
      - '.:/usr/src/hakhak'
    depends_on:
      - database
    command: 'yarn start:prod'
    networks:
      hakhak_net:
        ipv4_address: 172.16.25.3
networks:
  hakhak_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.25.0/24
